version: "3.8"

services:
  eatc-backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: eatc-backend-dev
    working_dir: /app/source/spring
    volumes:
      - ./source/spring:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn spring-boot:run

networks:
  eatc-net:
    external: true
